// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct METHOD_TYPE_AI_BT_DoAction { };
template<> inline behaviac::EBTStatus AI::_Execute_Method_<METHOD_TYPE_AI_BT_DoAction>()
{
	return this->AI::BT_DoAction();
}

struct METHOD_TYPE_AI_BT_SelectSkill { };
template<> inline behaviac::EBTStatus AI::_Execute_Method_<METHOD_TYPE_AI_BT_SelectSkill>()
{
	return this->AI::BT_SelectSkill();
}

struct METHOD_TYPE_AI_BT_SelectTarget { };
template<> inline behaviac::EBTStatus AI::_Execute_Method_<METHOD_TYPE_AI_BT_SelectTarget>()
{
	return this->AI::BT_SelectTarget();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
