// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "AI.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

AI::AI()
{
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

AI::~AI()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus AI::BT_DoAction()
{
///<<< BEGIN WRITING YOUR CODE BT_DoAction
	return behaviac::BT_INVALID;
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus AI::BT_SelectSkill()
{
///<<< BEGIN WRITING YOUR CODE BT_SelectSkill
	return behaviac::BT_INVALID;
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus AI::BT_SelectTarget()
{
///<<< BEGIN WRITING YOUR CODE BT_SelectTarget
	return behaviac::BT_INVALID;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
