// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_AI_H_
#define _BEHAVIAC_AI_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class AI : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE AI
///<<< END WRITING YOUR CODE
{
public:
	AI();
	virtual ~AI();

	BEHAVIAC_DECLARE_AGENTTYPE(AI, behaviac::Agent)

	private: behaviac::EBTStatus BT_DoAction();

	private: behaviac::EBTStatus BT_SelectSkill();

	private: behaviac::EBTStatus BT_SelectTarget();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
