// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline behaviac::EBTStatus FunctionPointer_AI_BT_DoAction(Agent* self) { return (behaviac::EBTStatus)((AI*)self)->_Execute_Method_<METHOD_TYPE_AI_BT_DoAction, behaviac::EBTStatus >(); }
	inline behaviac::EBTStatus FunctionPointer_AI_BT_SelectSkill(Agent* self) { return (behaviac::EBTStatus)((AI*)self)->_Execute_Method_<METHOD_TYPE_AI_BT_SelectSkill, behaviac::EBTStatus >(); }
	inline behaviac::EBTStatus FunctionPointer_AI_BT_SelectTarget(Agent* self) { return (behaviac::EBTStatus)((AI*)self)->_Execute_Method_<METHOD_TYPE_AI_BT_SelectTarget, behaviac::EBTStatus >(); }
	inline void FunctionPointer_AI_LogMessage(char* param0) { AI::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
